# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
