# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 20:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_auto_20160305_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='isValidated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z~\\.\\-_]+$', 'Only alphanumeric characters and ~/./-/_ are allowed.')], verbose_name='game path (on our site)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameSource',
            field=models.URLField(max_length=300, unique=True, verbose_name='game source URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Multiplayer', 'Multiplayer'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(blank=True, verbose_name='URL to image of game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image2',
            field=models.URLField(blank=True, verbose_name='secondary image URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='isPublic',
            field=models.BooleanField(default=False, verbose_name='is the game public? (You can always change this later)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=80, verbose_name='game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='price (€)'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='isDeveloper',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
