# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 21:13
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_game_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameSource',
            field=models.URLField(blank=True, max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Unspecified', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.URLField(default=builtins.id, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default=builtins.id, max_length=80),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
