# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20160303_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing')], default='Unspecified', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
