# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_auto_20160304_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesowned',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesowned',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Other', 'Other'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='gamesowned',
            name='paymentState',
            field=models.TextField(choices=[('success', 'Success'), ('error', 'Error'), ('cancel', 'Canceled'), ('dev', 'Developer'), ('in_progress', 'In Progress'), ('not_started', 'Not started')], default='not_started'),
        ),
    ]
