# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0006_auto_20160305_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='data',
            field=models.IntegerField(),
        ),
    ]
